"""Send email reminders with daily task brief."""

import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List, Dict, Any
from dotenv import load_dotenv

load_dotenv()


def format_task_brief(tasks: List[Dict[str, Any]]) -> str:
    """
    Format tasks as a nicely formatted email body.

    Args:
        tasks: List of enriched task dictionaries

    Returns:
        Formatted HTML email body
    """
    task_html = ""

    for i, task in enumerate(tasks, 1):
        analysis = task.get("analysis", {})
        priority_score = task.get("priority_score", 0)
        category = analysis.get("category", "unknown").upper()
        risk_level = analysis.get("risk_level", "unknown").upper()
        est_hours = analysis.get("estimated_hours", 0)
        notes = analysis.get("notes", "N/A")

        task_html += f"""
        <tr style="border-bottom: 1px solid #e0e0e0; padding: 15px 0;">
            <td style="padding: 10px; vertical-align: top;">
                <strong style="font-size: 16px; color: #1a1a1a;">{i}. {task['title']}</strong>
                <br/>
                <span style="color: #666; font-size: 13px;">Priority: {priority_score:.1f}</span>
            </td>
            <td style="padding: 10px; vertical-align: top; text-align: right;">
                <div style="background: #f0f0f0; padding: 8px 12px; border-radius: 4px; margin-bottom: 8px; font-size: 12px;">
                    <strong>{category}</strong><br/>
                    Risk: {risk_level}<br/>
                    Time: {est_hours}h
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="padding: 10px 0; color: #555; font-size: 14px; font-style: italic;">
                💡 {notes}
            </td>
        </tr>
        """

    return task_html


def send_daily_brief_email(recipient_email: str, tasks: List[Dict[str, Any]]) -> bool:
    """
    Send a formatted daily brief email.

    Args:
        recipient_email: Email address to send to
        tasks: List of enriched task dictionaries

    Returns:
        True if successful, False otherwise
    """
    gmail_email = os.getenv("GMAIL_EMAIL")
    gmail_password = os.getenv("GMAIL_PASSWORD")

    if not gmail_email or not gmail_password:
        print("Error: GMAIL_EMAIL or GMAIL_PASSWORD not set in .env")
        return False

    try:
        # Create message
        msg = MIMEMultipart("alternative")
        msg["Subject"] = "📋 Your Daily Task Brief"
        msg["From"] = gmail_email
        msg["To"] = recipient_email

        # Format task list
        task_html = format_task_brief(tasks)

        # Create HTML email body
        html = f"""
        <html>
            <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
                <h2 style="color: #1a1a1a; border-bottom: 2px solid #007bff; padding-bottom: 10px;">
                    📋 Your Daily Task Brief
                </h2>
                <p style="color: #666; font-size: 14px;">Good morning! Here are your top priorities for today.</p>

                <table style="width: 100%; margin: 20px 0; border-collapse: collapse;">
                    {task_html}
                </table>

                <div style="background: #f9f9f9; padding: 15px; border-left: 4px solid #007bff; margin-top: 20px; font-size: 13px; color: #666;">
                    <strong>💻 Smart Task CLI</strong><br/>
                    Run <code>task-cli daily-brief</code> anytime to see your full priorities.
                </div>

                <hr style="border: none; border-top: 1px solid #e0e0e0; margin: 20px 0;">
                <p style="font-size: 12px; color: #999; text-align: center;">
                    This email was generated by Smart Task CLI
                </p>
            </body>
        </html>
        """

        # Attach HTML part
        part = MIMEText(html, "html")
        msg.attach(part)

        # Send email via Gmail SMTP
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(gmail_email, gmail_password)
            server.sendmail(gmail_email, recipient_email, msg.as_string())

        print(f"✅ Email sent to {recipient_email}")
        return True

    except smtplib.SMTPAuthenticationError:
        print("Error: Gmail authentication failed. Check your email and app password.")
        return False
    except Exception as e:
        print(f"Error sending email: {e}")
        return False
